# Generated by Django 5.2.8 on 2025-11-29 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='menu_name',
            field=models.CharField(default='main_menu', max_length=50),
            preserve_default=False,
        ),
    ]
